CREATE DATABASE IF NOT EXISTS chu50_cartes CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE chu50_cartes;
CREATE TABLE IF NOT EXISTS cartes(
id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
matricule VARCHAR(100) NOT NULL UNIQUE,
nom VARCHAR(100) NOT NULL,
postnom VARCHAR(100) NOT NULL,
prenom VARCHAR(100) NOT NULL,
fonction VARCHAR(180) NOT NULL,
date_delivrance DATE NULL,
photo VARCHAR(255) NOT NULL,
photo_zoom DECIMAL(4,2) NOT NULL DEFAULT 1.00,
photo_x TINYINT UNSIGNED NOT NULL DEFAULT 50,
photo_y TINYINT UNSIGNED NOT NULL DEFAULT 30,
qr_url VARCHAR(500) NOT NULL,
statut ENUM('valide','inactive','annulee') NOT NULL DEFAULT 'valide',
date_creation DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
date_modification DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
KEY idx_nom(nom),KEY idx_postnom(postnom)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
